CREATE TABLE [dbo].[Purchasing Suppliers] (

	[SupplierID] int NULL, 
	[SupplierName] varchar(8000) NULL, 
	[SupplierCategoryID] int NULL, 
	[PrimaryContactPersonID] int NULL, 
	[AlternateContactPersonID] int NULL, 
	[DeliveryMethodID] int NULL, 
	[DeliveryCityID] int NULL, 
	[PostalCityID] int NULL, 
	[SupplierReference] varchar(8000) NULL, 
	[BankAccountName] varchar(8000) NULL, 
	[BankAccountBranch] varchar(8000) NULL, 
	[BankAccountCode] varchar(8000) NULL, 
	[BankAccountNumber] varchar(8000) NULL, 
	[BankInternationalCode] varchar(8000) NULL, 
	[PaymentDays] int NULL, 
	[InternalComments] varchar(8000) NULL, 
	[PhoneNumber] varchar(8000) NULL, 
	[FaxNumber] varchar(8000) NULL, 
	[WebsiteURL] varchar(8000) NULL, 
	[DeliveryAddressLine1] varchar(8000) NULL, 
	[DeliveryAddressLine2] varchar(8000) NULL, 
	[DeliveryPostalCode] varchar(8000) NULL, 
	[DeliveryLocation] varchar(8000) NULL, 
	[PostalAddressLine1] varchar(8000) NULL, 
	[PostalAddressLine2] varchar(8000) NULL, 
	[PostalPostalCode] varchar(8000) NULL, 
	[LastEditedBy] int NULL, 
	[ValidFrom] datetime2(6) NULL, 
	[ValidTo] datetime2(6) NULL
);