CREATE TABLE [dbo].[Sales Customers] (

	[CustomerID] int NULL, 
	[CustomerName] varchar(8000) NULL, 
	[BillToCustomerID] int NULL, 
	[CustomerCategoryID] int NULL, 
	[BuyingGroupID] int NULL, 
	[PrimaryContactPersonID] int NULL, 
	[AlternateContactPersonID] int NULL, 
	[DeliveryMethodID] int NULL, 
	[DeliveryCityID] int NULL, 
	[PostalCityID] int NULL, 
	[CreditLimit] decimal(38,6) NULL, 
	[AccountOpenedDate] date NULL, 
	[StandardDiscountPercentage] decimal(38,6) NULL, 
	[IsStatementSent] bit NULL, 
	[IsOnCreditHold] bit NULL, 
	[PaymentDays] int NULL, 
	[PhoneNumber] varchar(8000) NULL, 
	[FaxNumber] varchar(8000) NULL, 
	[DeliveryRun] varchar(8000) NULL, 
	[RunPosition] varchar(8000) NULL, 
	[WebsiteURL] varchar(8000) NULL, 
	[DeliveryAddressLine1] varchar(8000) NULL, 
	[DeliveryAddressLine2] varchar(8000) NULL, 
	[DeliveryPostalCode] varchar(8000) NULL, 
	[DeliveryLocation] varchar(8000) NULL, 
	[PostalAddressLine1] varchar(8000) NULL, 
	[PostalAddressLine2] varchar(8000) NULL, 
	[PostalPostalCode] varchar(8000) NULL, 
	[LastEditedBy] int NULL, 
	[ValidFrom] datetime2(6) NULL, 
	[ValidTo] datetime2(6) NULL
);