CREATE TABLE [Warehouse].[StockItems_Archive] (

	[StockItemID] int NULL, 
	[StockItemName] varchar(8000) NULL, 
	[SupplierID] int NULL, 
	[ColorID] int NULL, 
	[UnitPackageID] int NULL, 
	[OuterPackageID] int NULL, 
	[Brand] varchar(8000) NULL, 
	[Size] varchar(8000) NULL, 
	[LeadTimeDays] int NULL, 
	[QuantityPerOuter] int NULL, 
	[IsChillerStock] bit NULL, 
	[Barcode] varchar(8000) NULL, 
	[TaxRate] decimal(18,3) NULL, 
	[UnitPrice] decimal(18,2) NULL, 
	[RecommendedRetailPrice] decimal(18,2) NULL, 
	[TypicalWeightPerUnit] decimal(18,3) NULL, 
	[MarketingComments] varchar(8000) NULL, 
	[InternalComments] varchar(8000) NULL, 
	[Photo] varbinary(8000) NULL, 
	[CustomFields] varchar(8000) NULL, 
	[Tags] varchar(8000) NULL, 
	[SearchDetails] varchar(8000) NULL, 
	[LastEditedBy] int NULL, 
	[ValidFrom] datetime2(6) NULL, 
	[ValidTo] datetime2(6) NULL
);