CREATE TABLE [Sales].[Invoices] (

	[InvoiceID] int NULL, 
	[CustomerID] int NULL, 
	[BillToCustomerID] int NULL, 
	[OrderID] int NULL, 
	[DeliveryMethodID] int NULL, 
	[ContactPersonID] int NULL, 
	[AccountsPersonID] int NULL, 
	[SalespersonPersonID] int NULL, 
	[PackedByPersonID] int NULL, 
	[InvoiceDate] date NULL, 
	[CustomerPurchaseOrderNumber] varchar(8000) NULL, 
	[IsCreditNote] bit NULL, 
	[CreditNoteReason] varchar(8000) NULL, 
	[Comments] varchar(8000) NULL, 
	[DeliveryInstructions] varchar(8000) NULL, 
	[InternalComments] varchar(8000) NULL, 
	[TotalDryItems] int NULL, 
	[TotalChillerItems] int NULL, 
	[DeliveryRun] varchar(8000) NULL, 
	[RunPosition] varchar(8000) NULL, 
	[ReturnedDeliveryData] varchar(8000) NULL, 
	[ConfirmedDeliveryTime] datetime2(6) NULL, 
	[ConfirmedReceivedBy] varchar(8000) NULL, 
	[LastEditedBy] int NULL, 
	[LastEditedWhen] datetime2(6) NULL
);